# Generated by Django 5.1 on 2024-08-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='SchoolModel',
        ),
    ]
