# Generated by Django 5.1 on 2024-08-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_school_schoolmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('Stu_email', models.EmailField(max_length=254)),
                ('stu_roll', models.IntegerField()),
            ],
        ),
    ]
